# Dictionary mapping class IDs to card types for the dealer
dealer_class_mapping = {
    # Hearts
    "a1": "Ace of Hearts",
    "a2": "2 of Hearts",
    "a3": "3 of Hearts",
    "a4": "4 of Hearts",
    "a5": "5 of Hearts",
    "a6": "6 of Hearts",
    "a7": "7 of Hearts",
    "a8": "8 of Hearts",
    "a9": "9 of Hearts",
    "a10": "10 of Hearts",
    "a11": "Jack of Hearts",
    "a12": "Queen of Hearts",
    "a13": "King of Hearts",
    "ea1": "Ace of Hearts",
    "ea2": "2 of Hearts",
    "ea3": "3 of Hearts",
    "ea4": "4 of Hearts",
    "ea5": "5 of Hearts",
    "ea6": "6 of Hearts",
    "ea7": "7 of Hearts",
    "ea8": "8 of Hearts",
    "ea9": "9 of Hearts",
    "ea10": "10 of Hearts",
    "ea11": "Jack of Hearts",
    "ea12": "Queen of Hearts",
    "ea13": "King of Hearts",
    # Diamonds
    "b1": "Ace of Diamonds",
    "b2": "2 of Diamonds",
    "b3": "3 of Diamonds",
    "b4": "4 of Diamonds",
    "b5": "5 of Diamonds",
    "b6": "6 of Diamonds",
    "b7": "7 of Diamonds",
    "b8": "8 of Diamonds",
    "b9": "9 of Diamonds",
    "b10": "10 of Diamonds",
    "b11": "Jack of Diamonds",
    "b12": "Queen of Diamonds",
    "b13": "King of Diamonds",
    "eb1": "Ace of Diamonds",
    "eb2": "2 of Diamonds",
    "eb3": "3 of Diamonds",
    "eb4": "4 of Diamonds",
    "eb5": "5 of Diamonds",
    "eb6": "6 of Diamonds",
    "eb7": "7 of Diamonds",
    "eb8": "8 of Diamonds",
    "eb9": "9 of Diamonds",
    "eb10": "10 of Diamonds",
    "eb11": "Jack of Diamonds",
    "eb12": "Queen of Diamonds",
    "eb13": "King of Diamonds",
    # Spades
    "c1": "Ace of Spades",
    "c2": "2 of Spades",
    "c3": "3 of Spades",
    "c4": "4 of Spades",
    "c5": "5 of Spades",
    "c6": "6 of Spades",
    "c7": "7 of Spades",
    "c8": "8 of Spades",
    "c9": "9 of Spades",
    "c10": "10 of Spades",
    "c11": "Jack of Spades",
    "c12": "Queen of Spades",
    "c13": "King of Spades",
    "ec1": "Ace of Spades",
    "ec2": "2 of Spades",
    "ec3": "3 of Spades",
    "ec4": "4 of Spades",
    "ec5": "5 of Spades",
    "ec6": "6 of Spades",
    "ec7": "7 of Spades",
    "ec8": "8 of Spades",
    "ec9": "9 of Spades",
    "ec10": "10 of Spades",
    "ec11": "Jack of Spades",
    "ec12": "Queen of Spades",
    "ec13": "King of Spades",
    # Clubs
    "d1": "Ace of Clubs",
    "d2": "2 of Clubs",
    "d3": "3 of Clubs",
    "d4": "4 of Clubs",
    "d5": "5 of Clubs",
    "d6": "6 of Clubs",
    "d7": "7 of Clubs",
    "d8": "8 of Clubs",
    "d9": "9 of Clubs",
    "d10": "10 of Clubs",
    "d11": "Jack of Clubs",
    "d12": "Queen of Clubs",
    "d13": "King of Clubs",
    "ed1": "Ace of Clubs",
    "ed2": "2 of Clubs",
    "ed3": "3 of Clubs",
    "ed4": "4 of Clubs",
    "ed5": "5 of Clubs",
    "ed6": "6 of Clubs",
    "ed7": "7 of Clubs",
    "ed8": "8 of Clubs",
    "ed9": "9 of Clubs",
    "ed10": "10 of Clubs",
    "ed11": "Jack of Clubs",
    "ed12": "Queen of Clubs",
    "ed13": "King of Clubs",
    # Misc - Assuming these might be incorrect class labels or not directly mapping to specific cards
    "10": "misc",
    "9": "misc",
    "C6": "misc",
    "b87": "misc",
    "c7-": "misc",
    "cb1": "misc",
    "cb5": "misc",
    "continue": "misc",
    "endred": "misc",
    "gfg": "misc",
    "gg": "misc",
    "gg-": "misc",
}

# Dictionary mapping class IDs to card types for the dealer
dealer_class_mapping2 = {
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "J": "Jack",
    "Q": "Queen",
    "K": "King",
    "A": "Ace",
}

# Dictionary mapping class IDs to card types
class_mapping = {
    # Hearts
    "a1": "Ace of Hearts",
    "a2": "2 of Hearts",
    "a3": "3 of Hearts",
    "a4": "4 of Hearts",
    "a5": "5 of Hearts",
    "a6": "6 of Hearts",
    "a7": "7 of Hearts",
    "a8": "8 of Hearts",
    "a9": "9 of Hearts",
    "a10": "10 of Hearts",
    "a11": "Jack of Hearts",
    "a12": "Queen of Hearts",
    "a13": "King of Hearts",
    # Diamonds
    "b1": "Ace of Diamonds",
    "b2": "2 of Diamonds",
    "b3": "3 of Diamonds",
    "b4": "4 of Diamonds",
    "b5": "5 of Diamonds",
    "b6": "6 of Diamonds",
    "b7": "7 of Diamonds",
    "b8": "8 of Diamonds",
    "b9": "9 of Diamonds",
    "b10": "10 of Diamonds",
    "b11": "Jack of Diamonds",
    "b12": "Queen of Diamonds",
    "b13": "King of Diamonds",
    # Spades
    "c1": "Ace of Spades",
    "c2": "2 of Spades",
    "c3": "3 of Spades",
    "c4": "4 of Spades",
    "c5": "5 of Spades",
    "c6": "6 of Spades",
    "c7": "7 of Spades",
    "c8": "8 of Spades",
    "c9": "9 of Spades",
    "c10": "10 of Spades",
    "c11": "Jack of Spades",
    "c12": "Queen of Spades",
    "c13": "King of Spades",
    # Clubs
    "d1": "Ace of Clubs",
    "d2": "2 of Clubs",
    "d3": "3 of Clubs",
    "d4": "4 of Clubs",
    "d5": "5 of Clubs",
    "d6": "6 of Clubs",
    "d7": "7 of Clubs",
    "d8": "8 of Clubs",
    "d9": "9 of Clubs",
    "d10": "10 of Clubs",
    "d11": "Jack of Clubs",
    "d12": "Queen of Clubs",
    "d13": "King of Clubs",
    # Misc classes
    "10": "10",
    "9": "9",
    "g": "G",
    "gg": "GG",
    "b87": "8 of Diamonds",
    "continue": "Continue",
    "endred": "End Red",
    "Unknown": "Unknown"
}
